### ISSUE TITLE
Date/time stamp on news post

### ISSUE THREAD

**Issue by JonHawke** [jcbjoe/TheNewsTab#7]
Hello,

Firstly got to say I love the new extension!
Would it be possible to add a date/time stamp on the news articles?

**Comment by jcbjoe** [comment]
HI @icabbi-JonH 

Sure!

Ill make this a toggle-able feature so it can be turned on and off. Some people may prefer the cleanness of the current tiles.

Thanks,
Joe

**Comment by jcbjoe** [comment]
Dates have been added: https://github.com/jcbjoe/TheNewsTab/commit/94da487bb94abc89f3dd786f81c49416e56992c7

**Comment by jcbjoe** [comment]
![image](https://user-images.githubusercontent.com/3605644/107853366-6bf85880-6e0d-11eb-8638-bd9e6dbd8a14.png)
